# Configuration script to Travis-CI
language: python
python:
  - "3.3"
  - "3.4"
install:
# - python3 setup.py install
  - pip install coverage --use-mirrors
  - pip install python-coveralls --use-mirrors
script:
  - coverage run --source=src/ofxstatement setup.py test
  - python setup.py install
after_success:
  coveralls
